// 가상 이벤트 데이터 전용 설정
const today = '20241124'; // 2024년 11월 24일
let sequence = 1;

const generateEventId = (domain: 'A' | 'B' | 'C' | 'D' | 'E' | 'F'): string => {
  return `${domain}-${today}-${String(sequence++).padStart(3, '0')}`;
};

// events-data에서 사용하는 BaseEvent 구조를 이 파일에서도 그대로 정의
interface BaseEvent {
  eventId: string;
  id: string;
  type: string;
  title: string;
  time: string;
  location: string;
  description?: string;
  source?: string;
  risk: 'HIGH' | 'MEDIUM' | 'LOW';
  status: 'URGENT' | 'ACTIVE' | 'NEW' | 'IN_PROGRESS' | 'CLOSED';
  pScore?: number;
  domain: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
}

// 기존 allEvents 배열을 그대로 옮긴 가상 이벤트 데이터
export const MOCK_EVENTS: BaseEvent[] = [
  // A - 112 치안 · 방범
  {
    eventId: generateEventId('A'),
    id: 'event-1',
    type: '폭행 · 상해',
    title: '흉기 소지 남성 위협 행동',
    time: '18:42',
    location: '안양시 동안구 비산동 123-7',
    description: '112 신고자 "흉기 든 남성이 위협 중"',
    source: '안양112센터',
    risk: 'HIGH',
    status: 'URGENT',
    pScore: 92,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-2',
    type: '절도 · 강도',
    title: '상가 절도 의심, 현금 절취 포착',
    time: '18:33',
    location: '안양시 만안구 안양동 674',
    description: 'AI 감지: 가방에서 현금 다발을 넣는 장면 포착',
    source: 'AI',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 78,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-3',
    type: '차량도주 · 용의차량 추적',
    title: '오토바이 도주, 은행 강도 연관 의심',
    time: '18:21',
    location: '안양시 동안구 평촌대로 456',
    description: '도주 오토바이, 은행 강도와 연관 가능성',
    source: '안양112센터',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 85,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-4',
    type: '기물파손',
    title: '음주 난동 및 기물 파손 다수',
    time: '18:05',
    location: '안양시 만안구 석수동 시장로 789',
    description: '음주 난동 + 기물 파손 신고 다수',
    source: '안양112센터',
    risk: 'MEDIUM',
    status: 'NEW',
    pScore: 65,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-5',
    type: '실종 · 미아',
    title: '8세 남아 실종, 마지막 목격 30분 전',
    time: '17:50',
    location: '안양시 동안구 평촌동 123-45',
    description: '8세 남아 실종, 마지막 목격 30분 전',
    source: '안양112센터',
    risk: 'HIGH',
    status: 'URGENT',
    pScore: 88,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-6',
    type: '위험행동(흉기 소지 등)',
    title: '흉기 소지 위험 행동',
    time: '17:30',
    location: '안양시 만안구 안양역 앞 광장 1번 출구',
    description: 'AI 감지: 긴 물체 소지, 위협 행동',
    source: 'AI',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 90,
    domain: 'A',
  },

  // B - 119 재난 · 구조
  {
    eventId: generateEventId('B'),
    id: 'event-7',
    type: '화재(실화/의심)',
    title: '주택 2층 연기 발생, 주민 대피 중',
    time: '17:45',
    location: '안양시 동안구 비산동 205-12',
    description: '주택 2층에서 연기 발생, 주민 대피 중',
    source: '안양119센터',
    risk: 'HIGH',
    status: 'IN_PROGRESS',
    pScore: 88,
    domain: 'B',
  },
  {
    eventId: generateEventId('B'),
    id: 'event-8',
    type: '연기 감지',
    title: '산림 인접 연기 발생, 확산 위험',
    time: '16:30',
    location: '안양시 동안구 산림로 120-4',
    description: '산림 인접 밭에서 연기 발생, 확산 위험',
    source: 'AI',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 92,
    domain: 'B',
  },
  {
    eventId: generateEventId('B'),
    id: 'event-9',
    type: '교통사고(경상/중상)',
    title: '차량 3대 추돌, 부상자 2명',
    time: '16:30',
    location: '안양시 동안구 평촌대로 234',
    description: '차량 3대 추돌, 부상자 2명',
    source: '안양119센터',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 72,
    domain: 'B',
  },
  {
    eventId: generateEventId('B'),
    id: 'event-10',
    type: '쓰러짐(응급)',
    title: '보행 중 갑자기 쓰러짐, 응급 상황',
    time: '15:20',
    location: '안양시 만안구 안양역 앞 광장 1번 출구',
    description: '보행 중 갑자기 쓰러짐, 응급 상황',
    source: '안양119센터',
    risk: 'HIGH',
    status: 'IN_PROGRESS',
    pScore: 87,
    domain: 'B',
  },

  // C - 사회적 약자 보호
  {
    eventId: generateEventId('C'),
    id: 'event-11',
    type: '배회(장기)',
    title: '80대 남성, 2시간 이상 동일 구역 배회',
    time: '19:15',
    location: '안양시 동안구 평촌동 234-56',
    description: '80대 남성, 2시간 이상 동일 구역 배회',
    source: 'AI',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 68,
    domain: 'C',
  },
  {
    eventId: generateEventId('C'),
    id: 'event-12',
    type: '보호구역 이탈',
    title: '치매 노인 보호구역 이탈, 추적 중',
    time: '14:50',
    location: '안양시 만안구 안양동 567-89 (안양요양원)',
    description: '요양원에서 이탈, 현재 추적 중',
    source: '안양요양원',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 82,
    domain: 'C',
  },
  {
    eventId: generateEventId('C'),
    id: 'event-13',
    type: '약자 긴급 호출(단말기)',
    title: '노인 낙상, 응급실 이송 요청',
    time: '13:30',
    location: '안양시 동안구 평촌동 456-78',
    description: '노인 낙상, 응급실 이송 요청',
    source: '안양119센터',
    risk: 'MEDIUM',
    status: 'CLOSED',
    pScore: 60,
    domain: 'C',
  },
  {
    eventId: generateEventId('C'),
    id: 'event-14',
    type: '쓰러짐(고령자/약자)',
    title: '80대 여성 쓰러짐, 의식 확인 중',
    time: '12:20',
    location: '안양시 만안구 석수동 345-67',
    description: '80대 여성 쓰러짐, 의식 확인 중',
    source: 'AI',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 85,
    domain: 'C',
  },

  // D - AI 이상행동/상황
  {
    eventId: generateEventId('D'),
    id: 'event-15',
    type: '쓰러짐',
    title: '보행 중 갑자기 쓰러짐, 응급 상황',
    time: '19:30',
    location: '안양시 만안구 안양역 앞 광장 1번 출구',
    description: 'CCTV AI 감지: 보행 중 갑자기 쓰러짐',
    source: 'AI',
    risk: 'HIGH',
    status: 'URGENT',
    pScore: 87,
    domain: 'D',
  },
  {
    eventId: generateEventId('D'),
    id: 'event-16',
    type: '싸움/격투',
    title: '주먹 공격 행위 포착',
    time: '18:55',
    location: '안양시 동안구 비산동 345-67',
    description: 'AI 감지: 주먹으로 공격하는 행위 포착',
    source: 'AI',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 91,
    domain: 'D',
  },
  {
    eventId: generateEventId('D'),
    id: 'event-17',
    type: '무단침입/월담',
    title: '야간 상가 창문 부수고 침입 시도',
    time: '17:20',
    location: '안양시 만안구 안양동 중앙시장 123',
    description: '야간 상가 창문 부수고 침입 시도',
    source: 'AI',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 75,
    domain: 'D',
  },
  {
    eventId: generateEventId('D'),
    id: 'event-18',
    type: '배회',
    title: '3시간 이상 동일 구역 배회',
    time: '16:10',
    location: '안양시 동안구 평촌동 중앙공원 1',
    description: 'AI 감지: 3시간 이상 동일 구역 배회',
    source: 'AI',
    risk: 'MEDIUM',
    status: 'NEW',
    pScore: 58,
    domain: 'D',
  },

  // E - 재난(NDMS)
  {
    eventId: generateEventId('E'),
    id: 'event-19',
    type: '산불',
    title: '연기 발생, 산불 가능성',
    time: '15:45',
    location: '안양시 동안구 관악산로 567',
    description: '연기 발생, 산불 가능성',
    source: 'NDMS',
    risk: 'HIGH',
    status: 'IN_PROGRESS',
    pScore: 89,
    domain: 'E',
  },
  {
    eventId: generateEventId('E'),
    id: 'event-20',
    type: '호우(침수)',
    title: '시간당 50mm 이상 강우 예상',
    time: '14:00',
    location: '안양시 동안구 평촌동 일대',
    description: '시간당 50mm 이상 강우 예상',
    source: 'NDMS',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 70,
    domain: 'E',
  },
  {
    eventId: generateEventId('E'),
    id: 'event-21',
    type: '강풍·낙하물 위험',
    title: '강풍주의보, 낙하물 위험',
    time: '13:15',
    location: '안양시 만안구 안양동 일대',
    description: '강풍주의보 발령, 낙하물 위험',
    source: 'NDMS',
    risk: 'HIGH',
    status: 'ACTIVE',
    pScore: 83,
    domain: 'E',
  },

  // F - 도시 운영 · 환경
  {
    eventId: generateEventId('F'),
    id: 'event-22',
    type: 'IoT 장비 장애-오프라인',
    title: 'CCTV 센서 신호 이상, 오프라인',
    time: '12:30',
    location: '안양시 동안구 평촌대로 789',
    description: 'CCTV 센서 신호 이상, 오프라인 상태',
    source: 'IoT',
    risk: 'LOW',
    status: 'NEW',
    pScore: 45,
    domain: 'F',
  },
  {
    eventId: generateEventId('F'),
    id: 'event-23',
    type: '조명 인프라 이상-가로등',
    title: '가로등 5개 전원 차단',
    time: '11:20',
    location: '안양시 만안구 석수동 678-90',
    description: '가로등 5개 전원 차단',
    source: 'IoT',
    risk: 'LOW',
    status: 'NEW',
    pScore: 40,
    domain: 'F',
  },
  {
    eventId: generateEventId('F'),
    id: 'event-24',
    type: '교통 운영 이벤트-신호기',
    title: '교통 신호등 제어 시스템 오류',
    time: '10:15',
    location: '안양시 동안구 평촌대로 234',
    description: '교통 신호등 제어 시스템 오류',
    source: 'IoT',
    risk: 'MEDIUM',
    status: 'ACTIVE',
    pScore: 55,
    domain: 'F',
  },
  {
    eventId: generateEventId('F'),
    id: 'event-25',
    type: '환경 센서 이상-미세먼지',
    title: '미세먼지 센서 데이터 미전송',
    time: '09:30',
    location: '안양시 동안구 평촌동 890-12',
    description: '미세먼지 센서 데이터 미전송',
    source: 'IoT',
    risk: 'LOW',
    status: 'NEW',
    pScore: 35,
    domain: 'F',
  },
  // 일반 우선순위 이벤트들
  {
    eventId: generateEventId('A'),
    id: 'event-26',
    type: '소음 신고',
    title: '야간 소음 민원',
    time: '22:15',
    location: '안양시 동안구 비산동 345-67',
    description: '야간 소음 민원 접수',
    source: '안양112센터',
    risk: 'LOW',
    status: 'NEW',
    pScore: 30,
    domain: 'A',
  },
  {
    eventId: generateEventId('A'),
    id: 'event-27',
    type: '불만 접수',
    title: '주차장 불법주차 신고',
    time: '14:20',
    location: '안양시 만안구 안양동 123-45',
    description: '주차장 불법주차 신고',
    source: '안양112센터',
    risk: 'LOW',
    status: 'NEW',
    pScore: 25,
    domain: 'A',
  },
  {
    eventId: generateEventId('B'),
    id: 'event-28',
    type: '교통사고(경상)',
    title: '경미한 접촉 사고',
    time: '13:45',
    location: '안양시 동안구 평촌대로 567',
    description: '경미한 접촉 사고',
    source: '안양119센터',
    risk: 'LOW',
    status: 'NEW',
    pScore: 32,
    domain: 'B',
  },
  {
    eventId: generateEventId('C'),
    id: 'event-29',
    type: '배회(단기)',
    title: '단기 배회 행동 감지',
    time: '16:10',
    location: '안양시 만안구 석수동 789-01',
    description: '단기 배회 행동 감지',
    source: 'AI',
    risk: 'LOW',
    status: 'NEW',
    pScore: 28,
    domain: 'C',
  },
  {
    eventId: generateEventId('D'),
    id: 'event-30',
    type: '이상행동(저위험)',
    title: '정상 범위 내 이상 행동',
    time: '15:30',
    location: '안양시 동안구 비산동 456-78',
    description: '정상 범위 내 이상 행동',
    source: 'AI',
    risk: 'LOW',
    status: 'NEW',
    pScore: 22,
    domain: 'D',
  },
  {
    eventId: generateEventId('E'),
    id: 'event-31',
    type: '기상 정보',
    title: '보통 강수량 예상',
    time: '12:00',
    location: '안양시 전체',
    description: '보통 강수량 예상',
    source: 'NDMS',
    risk: 'LOW',
    status: 'NEW',
    pScore: 20,
    domain: 'E',
  },
  {
    eventId: generateEventId('F'),
    id: 'event-32',
    type: '환경 센서 이상',
    title: '온도 센서 일시적 오류',
    time: '11:45',
    location: '안양시 만안구 안양동 234-56',
    description: '온도 센서 일시적 오류',
    source: 'IoT',
    risk: 'LOW',
    status: 'NEW',
    pScore: 18,
    domain: 'F',
  },
  {
    eventId: generateEventId('F'),
    id: 'event-33',
    type: 'IoT 장비 장애',
    title: 'IoT 센서 데이터 지연',
    time: '10:30',
    location: '안양시 동안구 평촌동 567-89',
    description: 'IoT 센서 데이터 지연',
    source: 'IoT',
    risk: 'LOW',
    status: 'NEW',
    pScore: 15,
    domain: 'F',
  },
];


